# Generated by Django 3.2.13 on 2022-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing'), ('Health', 'Health'), ('Electronics', 'Electronics'), ('Recreational', 'Recreational'), ('Utility', 'Utility'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('expense_type', models.CharField(choices=[('Personal Use', 'Personal Use'), ('Bill Sharing', 'Bill Sharing'), ('Family Expense', 'Family Expense'), ('Lend', 'Lend'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Online Payment', 'Online Payment')], max_length=20)),
            ],
        ),
    ]
